### ISSUE TITLE
About a comparative experiment in the paper

### ISSUE THREAD

**Issue by TCBocean** [ihpdep/LDES#11]
Your work is great, providing a quick estimate of scale and rotation.
In the paper, one of your comparative experiments is to construct fDSST-LP, SAMF-LP and ECO-LP. Does the implementation of these functions include BSD iterations?

**Comment by TCBocean** [comment]
In addition, I have implemented ECO (displacement estimation) + FDSST (scale estimation) on C ++. I replaced fDSST with the scale estimation proposed in the paper, and did not add BSD iteration. The effect of the new combination is not as good as the original, and because the image rotation needs to be processed, the overall frame number is not as high as the original. I'm not sure whether my approach of directly replacing components in this way is consistent with the approach mentioned in the paper, because no more details are given in the paper.

**Comment by ihpdep** [comment]
Thanks for your interest in our work. The LP versions of these trackers do not include BCD iteration and do not include rotation estimation. As rotation is anyway an additional searching dimension, the speed and performance would be influenced by adding rotation estimation. 

In the paper, ECO-LP does not involve rotation estimation so the image rotation process is skipped. It also employs HoG as the feature in scale estimation. The log-polar template is resized to [128, 128]. The scale factor is set to 3 as

`tmp_scale_sz = floor((base_target_sz + sum(base_target_sz)/scale_factor));`

I think these are all the details. Good luck with your project!

**Comment by TCBocean** [comment]
WOW, thank you for your answer. I forgot to ask this question. I will try the experimental information you gave, thanks again.
