### ISSUE TITLE
Invalid MEX-file 'C:\LDES-master\utility\mexfiles\mpolar.mexw64': The specified module could not be found..

### ISSUE THREAD

**Issue by Adhders** [ihpdep/LDES#3]
我配置win10， matlab2016b, opencv2.4.11,一直运行失败，我重新mex编译也不行，我把compile.m的内容修改如下也不行！

mex -lopencv_core -lopencv_imgproc -L C:\opencv\build\x64\vc11\lib -I C:\opencv\build\include mexResize.cpp MxArray.cpp
mex -lopencv_core -lopencv_imgproc -L C:\opencv\build\x64\vc11\lib -I C:\opencv\build\include mpolar.cpp
mex -lopencv_core -lopencv_imgproc -L C:\opencv\build\x64\vc11\lib ...
    -I C:\opencv\build\include getColorSpace.cpp
mex -lopencv_core -lopencv_imgproc -L C:\opencv\build\x64\vc11\lib ...
    -I C:\opencv\build\include getColorSpaceHist.cpp

**Comment by ihpdep** [comment]
What is your error message?
